# Generated by Django 5.0 on 2023-12-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem1', models.CharField(max_length=50)),
                ('mem2', models.CharField(max_length=50)),
                ('mem3', models.CharField(max_length=50)),
                ('mem4', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
