# Generated by Django 5.0 on 2023-12-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_user_mem4_remove_user_mem4roll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Groupinfo',
        ),
    ]
