# Generated by Django 5.0 on 2023-12-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_user_groupinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='username', editable=False, max_length=50)),
                ('pdomain', models.TextField(default='000000', editable=False)),
                ('pguide', models.CharField(default='username', editable=False, max_length=200)),
            ],
            options={
                'db_table': 'projectinfo',
            },
        ),
    ]
